project_id = "fyloldkiuxtcdiazbtwn"

[functions.admin-complete-bot]
verify_jwt = false

[functions.track-login]
verify_jwt = true

[functions.get-weekly-login-stats]
verify_jwt = true

[functions.trading-bot-simulator]
verify_jwt = false

[functions.trading-bot-scheduler-v2]
verify_jwt = false

[functions.trading-bot-scheduler]
verify_jwt = false

[functions.crypto-price-scheduler]
verify_jwt = false

[functions.nowpayments-create-invoice]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.nowpayments-check-status]
verify_jwt = false

[functions.nowpayments-currencies]
verify_jwt = false

[functions.send-trade-notification]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-kyc-confirmation]
verify_jwt = false

[functions.send-kyc-rejection]
verify_jwt = false

[functions.send-bank-deposit-confirmation]
verify_jwt = false

[functions.send-crypto-deposit-confirmation]
verify_jwt = false

[functions.send-bank-kyc-confirmation]
verify_jwt = false

[functions.send-bank-kyc-rejection]
verify_jwt = false

[functions.send-credit-ident-approved]
verify_jwt = false

[functions.send-credit-approved]
verify_jwt = false

[functions.send-credit-rejected]
verify_jwt = false

[functions.send-credit-activated]
verify_jwt = false
