project_id = "fyloldkiuxtcdiazbtwn"

[functions.track-login]
verify_jwt = true

[functions.get-weekly-login-stats]
verify_jwt = true

[functions.trading-bot-simulator]
verify_jwt = false

[functions.trading-bot-scheduler-v2]
verify_jwt = false

[functions.trading-bot-scheduler]
verify_jwt = false

[functions.crypto-price-scheduler]
verify_jwt = false

[functions.nowpayments-create-invoice]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.nowpayments-check-status]
verify_jwt = false
